USE college_campus_portal_cloud;
ALTER TABLE users ADD COLUMN IF NOT EXISTS device_hash VARCHAR(128);
ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_image VARCHAR(255);
CREATE TABLE IF NOT EXISTS infrastructure_images (id BIGINT AUTO_INCREMENT PRIMARY KEY,title VARCHAR(255) NOT NULL,file_path VARCHAR(500) NOT NULL,uploaded_by INT NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(uploaded_by) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS site_content (content_key VARCHAR(100) PRIMARY KEY,title VARCHAR(255),body TEXT,updated_by INT NULL,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(updated_by) REFERENCES users(id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS tourism_places (id BIGINT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(180) NOT NULL UNIQUE,description TEXT NOT NULL,image_path VARCHAR(500),source_url VARCHAR(500),sort_order INT DEFAULT 0);
